const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';

const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';
const UPDATE_PAGE = 'UPDATE_PAGE';

module.exports = {
  FETCH_RESTAURANTS_REQUEST,
  FETCH_RESTAURANTS_SUCCESS,
  FETCH_RESTAURANTS_FAILURE,
  FILTER_RESTAURANTS,
  UPDATE_PAGE
}