const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';

module.exports = {
  FETCH_RESTAURANTS_REQUEST,
  FETCH_RESTAURANTS_SUCCESS,
  FETCH_RESTAURANTS_FAILURE
}